name: Build Image and deploy to GHCR
on: [push]

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GTIHUB_TOKEN }}

      - name: 'Build Image'
        run: |
          docker build -f Containerfile . ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
          docker push ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
